/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/unit_sprintf_tests.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>

#include "../s21_string.h"

#define STRING_LENGTH 50

START_TEST(string_without_format_test) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "Hello, world!");
  sprintf(buffer2, "Hello, world!");

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%d", 1234567890);
  sprintf(buffer2, "%d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_width_larger_than_length) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%20d", 1234567890);
  sprintf(buffer2, "%20d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_width_smaller_than_length) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%5d", 1234567890);
  sprintf(buffer2, "%5d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_width_munis_flag) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%-20d", 1234567890);
  sprintf(buffer2, "%-20d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_precision_smaller_than_length) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%.5d", 1234567890);
  sprintf(buffer2, "%.5d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_precision_larger_than_length) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%.20d", 1234567890);
  sprintf(buffer2, "%.20d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_flag_plus_positive_number) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%+d", 1234567890);
  sprintf(buffer2, "%+d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_flag_plus_negative_number) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%+d", -1234567890);
  sprintf(buffer2, "%+d", -1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_flag_space_positive_number) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "% d", 1234567890);
  sprintf(buffer2, "% d", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_flag_space_negative_number) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "% d", -1234567890);
  sprintf(buffer2, "% d", -1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_lengh_l) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%ld", 1234567890);
  sprintf(buffer2, "%ld", 1234567890);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_d_with_lengh_h) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%hd", 12345);
  sprintf(buffer2, "%hd", 12345);

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_c) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%c", 'a');
  sprintf(buffer2, "%c", 'a');

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_c_with_width) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%10c", 'a');
  sprintf(buffer2, "%10c", 'a');

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

START_TEST(specifier_c_with_width_flag_minus) {
  char buffer1[STRING_LENGTH + 1] = {0};
  char buffer2[STRING_LENGTH + 1] = {0};

  s21_sprintf(buffer1, "%-10c", 'a');
  sprintf(buffer2, "%-10c", 'a');

  ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

Suite *test_sprintf(void) {
  Suite *s = suite_create("Sprintf test");
  TCase *tc = tcase_create("Tests");

  tcase_add_test(tc, string_without_format_test);
  tcase_add_test(tc, specifier_d);
  tcase_add_test(tc, specifier_d_with_width_larger_than_length);
  tcase_add_test(tc, specifier_d_with_width_smaller_than_length);
  tcase_add_test(tc, specifier_d_with_width_munis_flag);
  tcase_add_test(tc, specifier_d_with_precision_smaller_than_length);
  tcase_add_test(tc, specifier_d_with_precision_larger_than_length);
  tcase_add_test(tc, specifier_d_with_flag_plus_positive_number);
  tcase_add_test(tc, specifier_d_with_flag_plus_negative_number);
  tcase_add_test(tc, specifier_d_with_flag_space_positive_number);
  tcase_add_test(tc, specifier_d_with_flag_space_negative_number);
  tcase_add_test(tc, specifier_d_with_lengh_l);
  tcase_add_test(tc, specifier_d_with_lengh_h);

  tcase_add_test(tc, specifier_c);
  tcase_add_test(tc, specifier_c_with_width);
  tcase_add_test(tc, specifier_c_with_width_flag_minus);

  suite_add_tcase(s, tc);

  return s;
}