/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/unit_sprintf_tests.check" instead.
 */

#include <check.h>

#include <stdlib.h>
#include <stdio.h>
#include "../s21_string.h"

START_TEST(s21_toint_test)
{
char buffer1[50] = { 0 };
char buffer2[50] = { 0 };
int number = 12345;
s21_sprintf(buffer1, "%d", number);
sprintf(buffer2, "%d", number);
ck_assert_str_eq(buffer1, buffer2);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_toint_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
