/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests_s21_sprintf.check" instead.
 */

#include <check.h>

#include <stdlib.h>
#include "s21_string.h"

START_TEST(s21_toint_test)
{
char* str = "";
ck_assert_int_eq(s21_strlen(str), strlen(str));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_toint_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
